version: "3"
services:
  neo4j:
    build:
      context: ./
      dockerfile: docker/Dockerfile-neo4j
    ports:
      - "127.0.0.1:7474:7474"
      - "127.0.0.1:7687:7687"
    volumes:
      - "./src:/app "
      - "./neo4j/data:/data "
      - "./neo4j/logs:/logs "
      - "./neo4j/import:/var/lib/neo4j/import "
      - "./neo4j/plugins:/plugins "
    environment:
      - "NEO4J_AUTH=neo4j/test"

  python:
    depends_on:
      - neo4j
    build:
      context: ./
      dockerfile: docker/Dockerfile-python
    ports: 
      - "127.0.0.1:8000:8000"
    volumes:
      - "./src:/app"